### ISSUE TITLE
[Bug] Navigation bar doesn't work

### ISSUE THREAD

**Issue by giveanornot** [jenny86520/aka-world#1]
#### Describe the bug:

I'm encountering hanging when clicking on each button in the navigation bar, which causes high CPU utilization.

#### Platform:

Manjaro Linux / Xorg / i3-gaps / Brave browser Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) unknown (64-bit)

**Comment by jenny86520** [comment]
Surprise !!
I already fix it.
unhm~


J.N. Yiunn ***@***.***> 於 2021年12月27日 週一 下午6:42寫道：

**Comment by giveanornot** [comment]
Great!
